const $ = id => document.getElementById(id); let assets = [], mode = "deep", tab;
const key = a => a.url;
function filtered() { const f = $("format").value, min = Number($("minSize").value); return assets.filter(a => (f === "all" || a.format === f) && (!min || !a.area || a.area >= min)); }
function render() { const list = filtered(), grid = $("grid"); $("count").textContent = `${list.length} assets · ${assets.length} unique`; grid.innerHTML = list.length ? list.map((a, i) => `<label class="card"><input type="checkbox" data-url="${encodeURIComponent(a.url)}" checked><img src="${a.url}" loading="lazy" onerror="this.style.opacity='.35'"><div class="meta">${a.format.toUpperCase()} · ${a.width || "?"}×${a.height || "?"}</div><div class="source" title="${a.source || ""}">${a.source || "unknown source"} · frame ${a.frameIndex ?? 0}</div></label>`).join("") : '<div class="empty">No matching assets found.</div>'; $("download").disabled = !list.length; }
async function scan() { $("status").textContent = `Scanning all frames (${mode === "deep" ? "CSS, Shadow DOM and legacy attributes" : "standard sources"})…`; assets = []; try { tab = (await chrome.tabs.query({active:true,currentWindow:true}))[0]; $("site").textContent = new URL(tab.url).hostname; await chrome.scripting.executeScript({target:{tabId:tab.id,allFrames:true},files:["scanner.js"],world:"ISOLATED"}); const results = await chrome.scripting.executeScript({target:{tabId:tab.id,allFrames:true},world:"ISOLATED",func:async()=>await (globalThis.__PAG_SCAN_RESULT || [])}); const map = new Map(); results.forEach((r, frameIndex) => (r.result || []).forEach(a => { a.frameIndex = frameIndex; if (!map.has(key(a))) map.set(key(a), a); })); assets = [...map.values()]; $("status").textContent = `Found ${assets.length} unique assets across ${results.length} frame(s).`; render(); } catch (e) { $("status").textContent = `Scan unavailable: ${e.message}`; $("grid").innerHTML = '<div class="empty">This page does not allow extension scanning.</div>'; } }
$("fast").onclick = () => { mode="fast"; $("fast").classList.add("active"); $("deep").classList.remove("active"); scan(); }; $("deep").onclick = () => { mode="deep"; $("deep").classList.add("active"); $("fast").classList.remove("active"); scan(); }; $("rescan").onclick = scan; $("format").onchange = render; $("minSize").onchange = render;
$("selectAll").onclick = () => document.querySelectorAll('#grid input').forEach(x => x.checked = true); $("clearAll").onclick = () => document.querySelectorAll('#grid input').forEach(x => x.checked = false);
$("download").onclick = async () => { const selected = [...document.querySelectorAll('#grid input:checked')].map(x => assets.find(a => a.url === decodeURIComponent(x.dataset.url))).filter(Boolean); if (!selected.length) return; $("download").disabled=true; $("progress").textContent=`0/${selected.length}`; const host = (()=>{try{return new URL(tab.url).hostname.replace(/[^a-z0-9.-]/gi,"_")}catch{return "page"}})(); const date = new Date().toISOString().slice(0,10); const r = await chrome.runtime.sendMessage({type:"download-assets",assets:selected,folder:`PageAssetGrabber/${host}_${date}`}); const failed=(r.results||[]).filter(x=>!x.ok).length; $("progress").textContent=failed?`${selected.length-failed} saved, ${failed} failed`:`${selected.length} saved`; $("download").disabled=false; };
chrome.runtime.onMessage.addListener(m => { if (m.type === "download-progress") $("progress").textContent=`${m.done}/${m.total}`; }); scan();
